In [24]:
#NUMPY
import numpy as np

#arr1 is a 1d array 
arr1=np.array([2,4,6,8,10,12,14,16,18,20])      
print(arr1)  

#indexing
print(arr1[8])  
print(arr1[4])

#slicing operation on 1D array
print(arr1[5:])  
print(arr1[:8])
print(arr1[5:8])
print(arr1[-4:0])
print(arr1[1:9:2])

#2D array of size 2 rows with 5 column
arr2=np.array([[12,13,14,16,18,20],[32,33,34,36,38,40]])
print(arr2)

#indexing 
print(arr2[1][4])
print(arr2[0][3])

#slicing operations in 2D
print(arr2[0,2:4])
print(arr2[1,0:3] )
print(arr2[0:1,2:5])
print(arr2[0:2,1:5])
 


[ 2  4  6  8 10 12 14 16 18 20]
18
10
[12 14 16 18 20]
[ 2  4  6  8 10 12 14 16]
[12 14 16]
[]
[ 4  8 12 16]
[[12 13 14 16 18 20]
 [32 33 34 36 38 40]]
38
16
[14 16]
[32 33 34]
[[14 16 18]]
[[13 14 16 18]
 [33 34 36 38]]


In [42]:
#NumPy Functions on 1d array as well as 2D array
import numpy as np

ones=np.ones(10)
zeros=np.zeros(2)
print(ones)
print(zeros)
 
 #1D array
data=np.array([100,99,98,97,96,95])
print("The dimension of the given array :",data.ndim)
print("The shape of the of the given array:",data.shape)
print("Size:",data.size)

#functions on 2D array
multiple=np.array([[52,34,56,78],[10,20,30,40],[99,88,77,66]])
print("The dimension of the second array:", multiple.ndim)
print("The shape of the second array:",multiple.shape)
print("Total number of elements:",multiple.size)

#sorting the array and finding the index of a element based on the condition
data1=np.array([100,45,87,8,110,55,456])
print(np.sort(data1))
result=np.where(data%2==0)
print(result)

#median and Mode functions
num_data=([34,56,6,23,23,75,9,100,110,6,35,87])
mean=np.mean(num_data)
median=np.median(num_data)

#mode functions
from scipy import stats
info=([90,78,6,5,4,55,55,6,78,55,55])
result1=stats.mode(info)
print(result1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0.]
The dimension of the given array : 1
The shape of the of the given array: (6,)
Size: 6
The dimension of the second array: 2
The shape of the second array: (3, 4)
Total number of elements: 12
[  8  45  55  87 100 110 456]
(array([0, 2, 4]),)
ModeResult(mode=array([55]), count=array([4]))


In [51]:
#PANDAS

import pandas as pd
list=['cara','sara','john']
df=pd.DataFrame(list)
print(df)

student_data={'Name':['Sara','Cara','Riya','Wyona'],'Age':[18,19,23,22], 'Qualification':['BCA','BSC','MCA','MCOM']}
df=pd.DataFrame(student_data)
print(df)
print(df[['Name','Age']])



      0
0  cara
1  sara
2  john
    Name  Age Qualification
0   Sara   18           BCA
1   Cara   19           BSC
2   Riya   23           MCA
3  Wyona   22          MCOM
    Name  Age
0   Sara   18
1   Cara   19
2   Riya   23
3  Wyona   22
